# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    
    pool: 
      vmImage: $(vmImageName)
    
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/UploadGit.Server.csproj'
    
  - job: Release
    displayName: Release to Azure
  
    pool: 
      vmImage: $(vmImageName)
  
    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish project
      inputs:
        command: 'publish'
        publishWebProjects: true
    
    

