# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


    
trigger:
- master

pool:
  vmImage: 'windows-latest'
variables:
  solution: '**/UploadGit.Server.csproj'
stages:
  - stage: build
    jobs: 
      - job: build
        steps:
        - task: UseDotNet@2
          displayName: 'Install .Net 5 SDK'
          inputs:
            packageType: 'sdk'
            version: '5.0.x'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '$(solution)'
          displayName: 'Build Server'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            projects: '$(solution)'
            arguments: '-o $(Build.ArtifactsStagingDirectory)'
          displayName: 'dotnet publish'


        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'

